/*
 * Copyright (c) 2026 European Commission
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European
 * Commission - subsequent versions of the EUPL (the "Licence"); You may not use this work
 * except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the Licence for the specific language
 * governing permissions and limitations under the Licence.
 */

package eu.europa.ec.commonfeature.interactor

import android.content.Context
import eu.europa.ec.businesslogic.validator.Form
import eu.europa.ec.businesslogic.validator.FormValidationResult
import eu.europa.ec.businesslogic.validator.FormValidator
import eu.europa.ec.businesslogic.validator.Rule as ValidationRule
import eu.europa.ec.testlogic.extension.runTest
import eu.europa.ec.testlogic.rule.CoroutineTestRule
import junit.framework.TestCase.assertEquals
import junit.framework.TestCase.assertFalse
import junit.framework.TestCase.assertTrue
import org.junit.After
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.mockito.Mock
import org.mockito.Mockito.mock
import org.mockito.MockitoAnnotations
import org.mockito.kotlin.any
import org.mockito.kotlin.argumentCaptor
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever

/**
 * The interactor's two remaining jobs, after the contract narrowed.
 *
 * The previous version of this file checked that `validateForm`/`validateForms` reached the validator
 * — delegation generated by `FormValidator by formValidator`, so it asserted Mockito rather than
 * behaviour. Those members are gone from the contract; what replaced them is one question,
 * `isScannedQrValid`, and *the rule it asks* is a real decision that moved here from the view-model.
 */
class TestQrScanInteractor {

    @get:Rule
    val coroutineRule = CoroutineTestRule()

    @Mock
    lateinit var formValidator: FormValidator

    private lateinit var closeable: AutoCloseable

    private lateinit var interactor: QrScanInteractor

    @Before
    fun before() {
        closeable = MockitoAnnotations.openMocks(this)

        interactor = QrScanInteractorImpl(
            formValidator = formValidator
        )
    }

    @After
    fun after() {
        closeable.close()
    }

    @Test
    fun `Given the validator accepts the scan, When isScannedQrValid is called, Then it is valid`() =
        coroutineRule.runTest {
            whenever(formValidator.validateForm(any())).thenReturn(FormValidationResult(isValid = true))

            assertTrue(interactor.isScannedQrValid("openid4vp://?request_uri=https%3A%2F%2Fv.test%2Fr"))
        }

    @Test
    fun `Given the validator rejects the scan, When isScannedQrValid is called, Then it is not valid`() =
        coroutineRule.runTest {
            whenever(formValidator.validateForm(any()))
                .thenReturn(FormValidationResult(isValid = false, message = "nope"))

            // The view-model counts these as failed scans and eventually shows its informative text,
            // so a mistake here is invisible until a user has scanned five good codes for nothing.
            assertFalse(interactor.isScannedQrValid("not a url"))
        }

    @Test
    fun `When isScannedQrValid is called, Then the scan is checked as a URL with a scheme and a query`() =
        coroutineRule.runTest {
            whenever(formValidator.validateForm(any())).thenReturn(FormValidationResult(isValid = true))
            val scanned = "openid4vp://?request_uri=https%3A%2F%2Fv.test%2Fr"

            interactor.isScannedQrValid(scanned)

            // The rule is the point. A wallet link carries its payload in the query and identifies
            // itself by scheme, while host and path are routinely absent — `openid4vp://?…` has no
            // host at all — so validating those would reject the very links this screen exists to read.
            val form = argumentCaptor<Form>()
            verify(formValidator).validateForm(form.capture())
            val (rules, value) = form.firstValue.inputs.entries.single()
            assertEquals(scanned, value)

            val rule = rules.single() as ValidationRule.ValidateUrl
            assertTrue(rule.shouldValidateSchema)
            assertTrue(rule.shouldValidateQuery)
            assertFalse(rule.shouldValidateHost)
            assertFalse(rule.shouldValidatePath)
        }

    // Case: launchRqesSdk behaviour
    // The function is a single-line delegation to the EudiRQESUi Kotlin object singleton
    // (an instance method on a singleton, not a Java static), so Mockito's mockStatic
    // cannot intercept the call. We exercise the line for coverage and tolerate any
    // throwable from the un-initialized SDK.
    @Test
    fun `When launchRqesSdk is called, Then the call is dispatched to the EudiRQESUi singleton`() {
        // Given
        val context = mock(Context::class.java)

        try {
            // When: the uri crosses as a String now, and this is where it becomes an android Uri again.
            interactor.launchRqesSdk(context = context, uri = "https://rqes.test/sign?doc=1")
        } catch (_: Throwable) {
            // Expected: SDK throws because setup() has not been called in unit-test context.
        }
    }
}
